apiVersion: v1
kind: Service
metadata:
  name: triton-svc
  namespace: vpr
spec:
  selector:
    app: triton
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: grpc
      port: 8001
      targetPort: 8001
    - name: metrics
      port: 8002
      targetPort: 8002
  type: ClusterIP    # Only accessible inside the cluster (FastAPI calls it internally)
